### ISSUE TITLE
New Material Buttons

### ISSUE THREAD

**Issue by JigneshWorld** [miquelbeltran/flutter_material_showcase#1]
New Material Buttons

https://flutter.dev/docs/release/breaking-changes/buttons
https://material.io/components/buttons/flutter

Would like to contribute as well..

**Comment by miquelbeltran** [comment]
Feel free to send a PR replacing the old buttons with the new Material ones! I would really appreciate it.

**Comment by JigneshWorld** [comment]
I am trying to add 3rd outlined button but button's label goes into 2nd line..
So, thinking to make those as a small single word label.

Attached ref images.

<img src="https://user-images.githubusercontent.com/7347854/111654475-cb8fbc80-882e-11eb-980a-95f3dca8fb7d.png" alt="buttons with full label" width="250"/>

<br>
---------
<br>

<img src="https://user-images.githubusercontent.com/7347854/111654726-05f95980-882f-11eb-8d2b-40ba576562e6.png" alt="buttons with single word label" width="250"/>

**Comment by Taosif7** [comment]
I think this is resolved now, we can close this issue @miquelbeltran
